name: Build Debug
on:
  push:
    branches:
      - '*'
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

jobs:
  BuildDebug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Checkout submodules
        run: git submodule update --init --recursive --remote --force

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Setup Gradle
        if: success()
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-home-cache-cleanup: true

      - name: Setup ninja
        uses: seanmiddleditch/gha-setup-ninja@v5

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.31.4'

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Debug Build
        run: ./gradlew --no-daemon app:assembleAlphaDebug
          
      - name: Upload Aritfact (universal)
        uses: actions/upload-artifact@v4
        if: ${{  success() }}
        with:
          name: CMFA Debug Unsigned APK (universal) 
          path: |
            app/build/outputs/apk/alpha/debug/*-universal-*.apk
      
      - name: Upload Aritfact (arm64-v8a)
        uses: actions/upload-artifact@v4
        if: ${{  success() }}
        with:
          name: CMFA Debug Unsigned APK (arm64-v8a)
          path: |
            app/build/outputs/apk/alpha/debug/*-arm64-v8a-*.apk
      
      - name: Upload Aritfact (armeabi-v7a)
        uses: actions/upload-artifact@v4
        if: ${{  success() }}
        with:
          name: CMFA Debug Unsigned APK (armeabi-v7a)
          path: |
            app/build/outputs/apk/alpha/debug/*-armeabi-v7a-*.apk
      
      - name: Upload Aritfact (x86_64)
        uses: actions/upload-artifact@v4
        if: ${{  success() }}
        with:
          name: CMFA Debug Unsigned APK (x86_64)
          path: |
            app/build/outputs/apk/alpha/debug/*-x86_64-*.apk
      
      - name: Upload Aritfact (x86)
        uses: actions/upload-artifact@v4
        if: ${{  success() }}
        with:
          name: CMFA Debug Unsigned APK (x86)
          path: |
            app/build/outputs/apk/alpha/debug/*-x86-*.apk
